#version: 2

version: 2



sources:
  - name: jaffle_shop
    database: postgres
    


    tables:
        - name: stg_customers
          columns:
            - name: customer_id
              tests:
                - row_count:
                    above: 300
            




#models:
#  - name: customers
#    tests:
#      - name: record_count_warning
#        description: "Send warning if fewer than 100 records are entered every time the table is updated"
#        severity: WARN
#        assertion: not_null_count('{{ this }}') >= 100





#version: 2

#models:
#  - name: customers
#    columns:
#      - name: customer_id
#        tests:
#          - unique
#          - not_null

#  - name: stg_customers
#    columns:
#      - name: customer_id
#        tests:
#          - unique
#          - not_null
          
#  - name: sample
#    columns:
#      - name: id
#        tests:
#          - unique
#          - not_null

#  - name: stg_orders
#    columns:
#      - name: order_id
#        tests:
#          - unique
#          - not_null
#      - name: status
#        tests:
#          - accepted_values:
#              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
#      - name: customer_id
#        tests:
#          - not_null
#          - relationships:
#              to: ref('stg_customers')
#              field: customer_id
              
              
 